mysite/enquetes/urls.py
from django.urls import path
from . import views

# Namespaces. Serve para identificar de qual url de determinada aplicação estamos nos referindo
app_name = 'enquetes'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detalhes/<int:pk>/', views.DetalhesView.as_view(), name='detalhes'),
    path('resultado/<int:pk>/', views.ResultadoView.as_view(), name='resultado'),
    path('votacao/<int:enquete_id>/', views.votacao, name='votacao'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('enquetes/', include('enquetes.urls')),
    #path('', include('enquetes.urls')),

]

mysite/enquetes/models.py
import datetime
from django.db import models
from django.utils import timezone

#As classes já definem uma chave primária automática 'ID'
#Neste caso é necessário definir os tipos dos atributos, pois aqui eles são bases dos atributos do banco de dados

#max_length: define uma quantidade limite de caracteres
#default: define um valor padrão para as pergutas
#on_delete: se uma pergunta for apagada todas as alternativas serão apagadas em forma de cascata

class Pergunta(models.Model):
    texto = models.CharField(max_length = 150)
    data_pub = models.DateTimeField('Data de publicação')

    def __str__(self):
        return '({}) - {}'.format(self.id, self.texto)

    def publicada_recentemente(self):
        return self.data_pub >= timezone.now() - datetime.timedelta(days=1)


class Alternativa(models.Model):
    texto = models.CharField(max_length = 80)
    quant_votos = models.IntegerField('Quantidade de votos', default = 0)
    pergunta = models.ForeignKey(Pergunta, on_delete = models.CASCADE)

    def __str__(self):
        return '({}) - {}'.format(self.id, self.texto)




#Eu posso ter uma Perguta relacionada a varias Alternativas, mas um Alternativa deve está relacionada a apenas uma Pergunta

mysite/enquetes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Pergunta, Alternativa
#from django.template import loader
from django.http import Http404
from django.views import generic



class IndexView(generic.ListView):
    model = Pergunta
    template_name = 'enquetes/index.html'
    context_object_name = 'lista_enquetes'
    def get_queryset(self):
        return Pergunta.objects.order_by('-data_pub')


class DetalhesView(generic.DetailView):
    model = Pergunta
    template_name = 'enquetes/detalhes.html'

class ResultadoView(generic.DetailView):
    model = Pergunta
    template_name = 'enquetes/resultado.html'


def votacao(request, enquete_id):
    try:
        pergunta = get_object_or_404(Pergunta, pk = enquete_id)
        alt_id = request.POST['alt']
        alternativa = pergunta.alternativa_set.get(pk=alt_id)

    except(KeyError, Alternativa.DoesNotExist):
        return render(request, 'enquetes/detalhes.html' , {'pergunta': pergunta,
        'error': 'Selecione uma alternativa válida'})
    else:
        alternativa.quant_votos += 1
        alternativa.save()
        return HttpResponseRedirect(reverse(
                'enquetes:resultado', args=(pergunta.id,)
            ))



"""
#### HISTÓRICO DAS VERSÕES ####
###############################

## VIEW INDEX ##
################
----versão 1
    resultado = ',<br/> '.join([p.texto for p in lista_enquetes])
    return HttpResponse(resultado)
----versão 2
    template = loader.get_template('enquetes/index.html')
    return HttpResponse(template.render(contexto, request))
----versão 3
def index(request):
    lista_enquetes = Pergunta.objects.order_by('-data_pub')[:10]
    contexto = { 'lista_enquetes': lista_enquetes }
    return render(request, 'enquetes/index.html', contexto)
----vesão 4
class IndexView(generic.ListView):
    template_name = 'enquetes/index.html'
    context_object_name = 'lista_enquetes'
    def get_queryset(self):
        return Pergunta.objects.order_by('-data_pub')

## VIEW DETALHES ##
###################
----versão 1
    retorno = "<h2>DETALHES da enquete de identificador = %s</h2>"
    return HttpResponse(retorno % enquete_id)
----versão 2
    try:
        pergunta = Pergunta.objects.get(pk = enquete_id)
    except Pergunta.DoesNotExist:
        raise Http404("Identificador de enquete inválido!")
----versão 3
def detalhes(request, enquete_id):
    pergunta = get_object_or_404(Pergunta, pk = enquete_id)
    return render(
        request, 'enquetes/detalhes.html', {'pergunta': pergunta}
    )
----versão 4
class DetalhesView(generic.DetailView):
    model = Pergunta
    template_name = 'enquetes/detalhes.html'
## VIEW RESULTADO ##
####################
----versão 1
def resultado(request, enquete_id):
    pergunta = get_object_or_404(Pergunta, pk = enquete_id)
    return render(
        request, 'enquetes/resultado.html', {'pergunta': pergunta}
    )
----versão 2
class ResultadoView(generic.DetailView):
    model = Pergunta
    template_name = 'enquetes/resultado.html'
## VIEW VOTACAO ##
##################

"""

mysite/enquetes/templates/enquetes/detalhes.html
<html>
    <head>
        <tittle>App Enquetes</tittle>
    </head>
    <body>
        <h1>Aplicação de Enquetes</h1>
        <h2>Detalhes da Enquete #{{pergunta.id}}</h2>
        <h3>{{pergunta.texto}}</h3>
        Escolha a alternativa desejada: <br/>
        {%if error%}
            <h3>{{error}}</h3>
        {%endif%}
        <ul>
        <form action="{% url 'enquetes:votacao' pergunta.id %}" method='post'>
            {% csrf_token %}
            {% for alt in pergunta.alternativa_set.all %}

                <li> <input type="radio" name="alt" value="{{ alt.id }}" id="alt{{forloop.counter}}" />
                <label for="alt{{forloop.counter}}">
                    {{alt.texto}}
                </label>
                </li>
            {%endfor%}

        <input type="submit" value="Votar"/>
        </form>
        </ul>
        <hr/>

        <a href="{% url 'enquetes:index' %}">Voltar</a>
    </body>
</html>

mysite/enquetes/templates/enquetes/index.html
<html>
    <head>
        <title>App Enquetes</title>
    </head>

    <body>
        <h1>Aplicação de Enquetes</h1>
        <h3>(DsWen 2022.2)</h3>
        {% if lista_enquetes %}
            <ul>
                {%for pergunta in lista_enquetes %}
                    <li><a href="{% url 'enquetes:detalhes' pergunta.id %}"/>
                        {{pergunta.texto}}
                    </a></li>
                {%endfor%}
            </ul>
        {%else%}
            <h3>Não existem questões disponíveis</h3>
        {% endif %}
    </body>
</html>

mysite/enquetes/templates/enquetes/resultado.html
<html>
    <head>
        <tittle>App Enquetes</tittle>
    </head>
    <body>
        <h1>Aplicação de Enquetes</h1>
        <h2>Resulta parcial da Enquete #{{pergunta.id}}</h2>
        <h3>{{pergunta.texto}}</h3>
        <ul>

            {% csrf_token %}
            {% for alt in pergunta.alternativa_set.all %}

                <li>
                    {{alt.texto}} = {{alt.quant_votos }}
                </li>
            {%endfor%}

        </ul>
        <hr/>
        <a href="{% url 'enquetes:index' %}">Voltar</a>
        | <a href="{% url 'enquetes:detalhes' pergunta.id%}">Votar novamente</a>
    </body>
</html>